#define GWL_EXSTYLE (-20)
#define GWL_STYLE (-16)
#define GWL_WNDPROC (-4)
#define GWL_HINSTANCE (-6)
#define GWL_HWNDPARENT (-8)
#define GWL_ID (-12)
#define GWL_USERDATA (-21)
#define DWL_DLGPROC 4
#define DWL_MSGRESULT 0
#define DWL_USER 8
