#define MFT_STRING 0
#define MFT_BITMAP 4
#define MFT_MENUBARBREAK 32
#define MFT_MENUBREAK 64
#define MFT_OWNERDRAW 256
#define MFT_RADIOCHECK 512
#define MFT_RIGHTJUSTIFY 0x4000
#define MFT_SEPARATOR 0x800
#define MFT_RIGHTORDER 0x2000

#define MFS_CHECKED 8
#define MFS_DEFAULT 4096
#define MFS_DISABLED 3
#define MFS_ENABLED 0
#define MFS_GRAYED 3
#define MFS_HILITE 128
#define MFS_UNCHECKED 0
#define MFS_UNHILITE 0

#define HBMMENU_CALLBACK (-1)
#define HBMMENU_SYSTEM (1)
#define HBMMENU_MBAR_RESTORE (2)
#define HBMMENU_MBAR_MINIMIZE (3)
#define HBMMENU_MBAR_CLOSE (5)
#define HBMMENU_MBAR_CLOSE_D (6)
#define HBMMENU_MBAR_MINIMIZE_D (7)
#define HBMMENU_POPUP_CLOSE (8)
#define HBMMENU_POPUP_RESTORE (9)
#define HBMMENU_POPUP_MAXIMIZE (10)
#define HBMMENU_POPUP_MINIMIZE (11)

